Repository mxschool/mxMoodle, pull requests merged in 2021-07, with the labels that each got.

#87 Covid email
  local/mxschool/classes/local/healthpass/healthcenter_notification.php
  local/mxschool/classes/local/healthpass/preferences_form.php
  local/mxschool/classes/local/healthtest/healthtest_notification.php
  local/mxschool/classes/local/healthtest/preferences_form.php
  local/mxschool/healthpass/preferences.php
  local/mxschool/healthtest/preferences.php
  local/mxschool/lang/en/local_mxschool.php
  local/mxschool/version.php
Labels: enhancement

#90 Faculty code
  local/mxschool/classes/local/user_management/faculty_edit_form.php
  local/mxschool/classes/local/user_management/faculty_table.php
  local/mxschool/db/install.xml
  local/mxschool/db/upgrade.php
  local/mxschool/lang/en/local_mxschool.php
  local/mxschool/user_management/faculty_edit.php
  local/mxschool/version.php
Labels: enhancement

#88 Created capability to access the Deans Permission Form
  local/mxschool/db/access.php
  local/mxschool/db/upgrade.php
  local/mxschool/deans_permission/form.php
  local/mxschool/lang/en/local_mxschool.php
Labels: enhancement

#100 Documentation Update
  docs/ABOUT_US.md
Labels: Documentation

#99 2021 healthpass
  blocks/mxschool_dash_dean/block_mxschool_dash_dean.php
  blocks/mxschool_dash_dean/lang/en/block_mxschool_dash_dean.php
  blocks/mxschool_dash_healthcenter/README.md
  blocks/mxschool_dash_healthcenter/block_mxschool_dash_healthcenter.php
  blocks/mxschool_dash_healthcenter/classes/privacy/provider.php
  blocks/mxschool_dash_healthcenter/db/access.php
  blocks/mxschool_dash_healthcenter/lang/en/block_mxschool_dash_healthcenter.php
  blocks/mxschool_dash_healthcenter/version.php
  blocks/mxschool_dash_healthpass/version.php
  docs/ABOUT_US.md
  docs/CODING_STYLE.md
  local/mxschool/classes/local/healthtest/audit_table.php
  local/mxschool/db/access.php
  local/mxschool/db/install.php
  local/mxschool/db/install.xml
  local/mxschool/db/upgrade.php
  local/mxschool/healthtest/audit_report.php
  local/mxschool/healthtest/block_report.php
  local/mxschool/healthtest/index.php
  local/mxschool/healthtest/test_report.php
  local/mxschool/lang/en/local_mxschool.php
  local/mxschool/locallib.php
  local/mxschool/version.php
Labels: enhancement

#103 2021 healthpass
  local/mxschool/classes/local/healthtest/audit_table.php
  local/mxschool/healthtest/audit_report.php
  local/mxschool/lang/en/local_mxschool.php
  local/mxschool/version.php
Labels: bug
